### ISSUE TITLE
am/pm is missing from Date/Time on imported photos

### ISSUE THREAD

**Issue by averixus** [marchyman/GeoTag#15] opened 2020-01-18 12:08 UTC
When I import photos, the Date/Time field is missing the am/pm value. This seems to prevent GeoTag from understanding the Date/Time value at all.

Here is the inspector in Preview, showing the Date Time correctly with its am value:

<img width="1027" alt="Screenshot 2020-01-18 at 12 02 46 pm" src="https://user-images.githubusercontent.com/9510882/72663440-b5982900-39ea-11ea-8129-5e287117baf8.png">

Here is the list in GeoTag when the file is imported, the Date/Time looks correct except that it's missing the am/pm:

<img width="531" alt="Screenshot 2020-01-18 at 12 03 07 pm" src="https://user-images.githubusercontent.com/9510882/72663447-c9dc2600-39ea-11ea-8eed-4e0e6abb11d5.png">

This prevents the 'interpolate location from track' from working (clicking it does nothing, the location fields stay blank). Opening the Date/Time editor shows that GeoTag doesn't understand the timestamp at all, and interprets it as the default 1970:

<img width="417" alt="Screenshot 2020-01-18 at 12 03 13 pm" src="https://user-images.githubusercontent.com/9510882/72663461-f55f1080-39ea-11ea-9241-aadbd07e0160.png">

Am I doing something wrong? The time on my camera is set correctly (also evident from the fact the Preview and Finder *are* understanding the timestamps and including the am/pm).

**Comment by JayAvery** [comment] 2020-01-18 12:20
Extra info: I just tried using exiftool's geotag feature directly to see if it was something up with my input files - and it worked fine and correctly interpolated the location from the gpx.

**Comment by marchyman** [comment] 2020-01-20 00:40
The date/time column uses a 24 hour format.  10:53:23 is 10 AM.  The reported value would be 22:53:23 for 10 PM.  It is the same format used by ExifTool.

But that doesn't explain your other issues.  Can you send me a copy of the image to see if I can reproduce the issue?

**Comment by JayAvery** [comment] 2020-01-20 16:25
The date/time column doesn't seem to use a 24 hour format to me! Here is what happens when I import two photos, and then manually edit the date/time on one of them to give it the value it already had:

<img width="529" alt="Screenshot 2020-01-20 at 4 16 46 pm" src="https://user-images.githubusercontent.com/9510882/72741971-aa86f980-3ba0-11ea-9776-bee68e83d921.png">

The top photo has it in 24-hour format which doesn't get interpreted correctly, and the bottom photo has it in am/pm format and it works as it should.

Here is the unedited file: 
 https://user-images.githubusercontent.com/9510882/72742181-19645280-3ba1-11ea-8552-3ad1ef988ad7.JPG

(I just double-checked the metadata wasn't changed by the upload process by saving it from there and the same thing happens - 24-hour format time that GeoTag doesn't read properly)

**Comment by marchyman** [comment] 2020-01-20 20:17
Thank you Jay,


> The top photo has it in 24-hour format which doesn't get interpreted correctly, and the bottom photo has it in am/pm format and it works as it should.

Yeah, that’s not right.   I’ll start looking at it now. And thanks for sending the image, too.  One anomaly is that exiftool is showing two instances of Create Date, Modify Date, and Date/Time Original, one with hundredths of second indicated, one not.  

Modify Date                     : 2020:01:20 13:41:42
Date/Time Original              : 2020:01:20 13:41:42
Create Date                     : 2020:01:20 13:41:42
Create Date                     : 2020:01:20 13:41:42.55
Date/Time Original              : 2020:01:20 13:41:42.55
Modify Date                     : 2020:01:20 13:41:42.55

That is something I’d not noticed before. GeoTag uses exiftool to update metadata but extracts the initial values use macOS functions.  I now wonder which version the macOS functions are returning and if GeoTag handles it right.

Marc

**Comment by marchyman** [comment] 2020-02-08 01:56
The date picker used to modify date/time does not allow me to change the date/time format.  That's why it shows AM/PM.  I don't yet know why GeoTag displayed one of the timestamps with an AM/PM indicator.  More importantly I don't know why the difference in display format causes one image to match the track log while the other fails.  Internally the dates should be the same.

Still looking at the issue.

**Comment by marchyman** [comment] 2023-01-18 03:17
No resolution, but no other complaints, either.  I think this was an Apple thing due to the duplicate timestamps.  Yeah, that may be my way of dodging the issue.  Since I have no control over the date/time picker so I'm going to close this issue.

**Closed by marchyman** 2023-01-18 03:17 UTC
