### ISSUE TITLE
No longer able to zoom map to coordinates

### ISSUE THREAD

**Issue by mxcolin** [marchyman/GeoTag#49] opened 2024-05-15 22:14 UTC
There used to be a capability in the previous version where you could copy and paste in coordinates and the map would zoom to those coordinates and set the image to that location. E.g.

43.6764775,4.6298813

would zoom and set this location. This now brings up a search result which you must click and then the map zooms there but does not set the Lat/Long. This has added several more clicks to the workflow of setting Lat/long on an image than in previous versions.

**Comment by marchyman** [comment] 2024-05-15 22:29
Ahh, yes.  I see.  That is a regression.  It is partly intentional in that I made a decision to not apply search results to selected images, but I do not remember the reason why.  I've noted the issue in the README and will address it in a future release.

**Comment by marchyman** [comment] 2024-05-15 22:39
Oh, I remember.  If you copy the coords in the appropriate format you can paste them directly into selected images.  You do not need to use map search.   The needed format is "lat | lon" or "lat, lon".   Note that you need a space following the comma when using it is a separator.  And there is still a bug because the map isn't updated to show the new location.

**Comment by marchyman** [comment] 2024-05-16 19:44
The fix has been committed and will be included in the next release.
- selected items will be assigned the location
- the map will zoom in when the camera "distance" is greater than 1000 meters
- Hitting enter in the search field will automatically select the first search result negating the need to select it with your mouse.

**Closed by marchyman** 2024-05-16 19:44 UTC
