### ISSUE TITLE
Search results should match those of Apple Maps’ search

### ISSUE THREAD

**Issue by elmimmo** [marchyman/GeoTag#52] opened 2024-05-30 00:46 UTC
Searches that produce concrete locations on Apple Maps produce none in GeoTag. I would have expected both to produce the same ones.

## Steps to reproduce:

1. Open GeoTag.
2. In the search box in the map panel, enter "京橋築地小学校" without quotation marks and press Enter.
3. Open Apple Maps.
4. In the Search box, enter "京橋築地小学校" without quotation marks and press Enter.

## Expected results

GeoTag (2) and Apple Maps (4) should produce the same location.

## Actual results

Apple Maps (4) produces a concrete location whereas GeoTag (2) produces none.

## Notes

Similar with "埼玉県比企郡滑川町中尾947", only that, with that one, Apple Maps’ behavior is also sketchy: pressing Enter produces no location whatsoever, but before pressing Enter two pop-up locations are suggestion, the first of them being the correct one. GeoTag, as before, produces no result at all.

**Comment by marchyman** [comment] 2024-05-30 00:58
I can confirm that GeoTag does not provide a location for that search.   I do not know why.  GeoTag is using Apple's MapKit search functionality and I'd have expected similar results.  I say similar as I've discovered that search results are not deterministic.  Perhaps I'm doing something wrong.

Thank you for the report.

**Comment by marchyman** [comment] 2024-05-30 01:17
Oops.  For some reason I was limiting search results to "address" types.  When that limitation is removed the search result looks like this:

![Screenshot 2024-05-29 at 6 11 36 PM](https://github.com/marchyman/GeoTag/assets/784627/2d806838-8a60-4314-8392-1649d155537b)

The change has been committed to the "fixes" branch and will be part of the next release, probably around the middle of next month.  Thank you again for your report.

**Closed by marchyman** 2024-05-30 01:17 UTC
